### ISSUE TITLE
Convert to use the new juju schema

### ISSUE THREAD

**Issue by SimonRichardson** [juju/js-libjuju#35]
Both [pylibjuju](https://github.com/juju/python-libjuju/blob/master/juju/client/schemas-juju-2.6.3.json) and [jslibjuju](https://github.com/juju/js-libjuju/blob/master/schemas/schema.json) rely on a schema for generating the facades and definitions. Considering that [juju now builds the schema directly](https://github.com/juju/juju/blob/develop/apiserver/facades/schema.json) for every change to the API server. We should consider if there is a way to converge to using the schema that juju outputs. 

That way you don't need tools like [jujuapidoc](https://github.com/juju/jujuapidoc), which will now become unsupported, unless someone steps up?

**Comment by SimonRichardson** [comment]
🎉

**Comment by hatched** [comment]
Couldn't have done it without your help 👍
