### ISSUE TITLE
Document `user-admin` Nuance Necessary to Log In as the Admin User

### ISSUE THREAD

**Issue by zicklag** [juju/js-libjuju#38]
I just found out that if you want to log in as the `admin` user, you have to pass the username as `user-admin` instead of `admin` or else you get this error: `"admin" is not a valid tag`. That was super confusing. It would be a good thing to have in the docs. I just noticed that it was the default username in the examples and that seemed suspicious enough to try.

**Comment by hatched** [comment]
Thanks for pointing this out...

Juju uses "tags" (`user-`, `machine-`, `credential-`) in a number of places and I think that I'd probably want the library to abstract those away for the user vs having to document what each tag is supposed to be.

**Comment by zicklag** [comment]
:+1:  I'd definitely prefer abstractions in the API than documentation too.

**Comment by anthonydillon** [comment]
Jeff can you add a priority label.
