### ISSUE TITLE
Document Needing `keep_classnames: true` When Bundling With Webpack/Terser

### ISSUE THREAD

**Issue by zicklag** [juju/js-libjuju#39]
After some debugging I found out that this library does not build correctly with Webpack's out-of-the-box Terser minfier settings.

You have to make sure to pass `keep_classnames: true` in the Terser settings. For Webpack you can see how to set the Terser settings [here](https://webpack.js.org/plugins/terser-webpack-plugin/).

**Comment by hatched** [comment]
Yep, this is a known issue, it'll be resolved with the new rebuild.
