### ISSUE TITLE
Failed request response is incorrectly handled

### ISSUE THREAD

**Issue by hatched** [juju/js-libjuju#65]
An RPC call can fail for two reasons:
- The request itself fails, typically because you do not have permissions to perform said request.
- The response has encountered an error while performing the request.

In the latter the error is returned as part of the response type [example](https://github.com/juju/js-libjuju/blob/6b2006a3af6f3daa09a4dc0da50087715c12c348/api/facades/client-v2.ts#L53)
```ts
interface AddMachinesResult {
  error?: Error;
  machine: string;
}
```

In the former however the [handler function](https://github.com/juju/js-libjuju/blob/6b2006a3af6f3daa09a4dc0da50087715c12c348/api/client.ts#L445) will replace the response value with the error value. 
```js
callback(resp.error || resp.response);
```

This is an issue because calls like the following are only reporting a response value for the successful path and not the potential error response.
```ts
const status = await conn.facades.client.fullStatus()
```

**Comment by huwshimi** [comment]
Resolved in https://github.com/juju/js-libjuju/pull/123
